on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6

      - name: Release
        run: |
          VERSION=${{ github.ref_name }}
          qgis-plugin-ci release ${VERSION} \
          --github-token ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload release assets
#        uses: actions/upload-artifact@v4
#        with:
#          name: test_plugin.${{ github.ref_name }}
#          path: ./test_plugin.${{ github.ref_name }}.zip